# Site settings
title: Aman Tomar blog
email: 
description: "Musings of a Computer Scientist."
baseurl: ""
url: "http://AmanTomar7.github.io"
github_username:  AmanTomar7

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge